// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gendep

import (
	"slices"
	"testing"
)

const shippedTable = "package parser\n\ntype TransitionTable []byte\n\nfunc GenerateTransitionTable() TransitionTable { return nil }\n\nvar Table = GenerateTransitionTable()\n"
const generatedTable = "package parser\n\n// Code generated by gen.go. DO NOT EDIT.\n\nvar Table = TransitionTable{1}\n"

// The x/ansi shape: the module ships a table it builds at run time, and its
// generator writes a precomputed one beside it. Keeping both declares Table
// twice, so the generated file goes.
func TestAGeneratedFileLosesToTheModulesOwnDeclaration(test *testing.T) {
	modroot := writeTree(test, test.TempDir(), map[string]string{
		"parser/transition_table.go": shippedTable,
	})
	stage := writeTree(test, test.TempDir(), map[string]string{
		"parser/transition_table.go": shippedTable,
		"parser/table.go":            generatedTable,
	})

	if got := superseded(modroot, stage, []string{"parser/table.go"}); !slices.Equal(got, []string{"parser/table.go"}) {
		test.Errorf("superseded = %v, want the generated file", got)
	}
}

// The half a package is missing declares names nothing else does, which is what
// completing a module is for. It stays.
func TestTheMissingHalfOfAPackageIsKept(test *testing.T) {
	const shipped = "package catalog\n\nvar Names = names()\n"
	const generated = "package catalog\n\nfunc names() []string { return nil }\n"
	modroot := writeTree(test, test.TempDir(), map[string]string{
		"catalog/catalog.go": shipped,
	})
	stage := writeTree(test, test.TempDir(), map[string]string{
		"catalog/catalog.go":   shipped,
		"catalog/names.gen.go": generated,
	})

	if got := superseded(modroot, stage, []string{"catalog/names.gen.go"}); len(got) != 0 {
		test.Errorf("superseded = %v, want nothing dropped", got)
	}
}

// One package's collision costs that package alone.
func TestOnlyTheCollidingPackageDropsWhatItGenerated(test *testing.T) {
	const other = "package other\n\nvar Kept = 1\n"
	const gen = "package other\n\nvar Fresh = 2\n"
	modroot := writeTree(test, test.TempDir(), map[string]string{
		"parser/transition_table.go": shippedTable,
		"other/other.go":             other,
	})
	stage := writeTree(test, test.TempDir(), map[string]string{
		"parser/transition_table.go": shippedTable,
		"parser/table.go":            generatedTable,
		"other/other.go":             other,
		"other/fresh.go":             gen,
	})

	got := superseded(modroot, stage, []string{"other/fresh.go", "parser/table.go"})
	if !slices.Equal(got, []string{"parser/table.go"}) {
		test.Errorf("superseded = %v, want the parser file alone", got)
	}
}

// A package drops everything its generator wrote once one file collides. Half a
// package compiles against a half it never finished.
func TestACollidingPackageDropsEveryFileItGenerated(test *testing.T) {
	const helper = "package parser\n\nvar Helper = 3\n"
	modroot := writeTree(test, test.TempDir(), map[string]string{
		"parser/transition_table.go": shippedTable,
	})
	stage := writeTree(test, test.TempDir(), map[string]string{
		"parser/transition_table.go": shippedTable,
		"parser/table.go":            generatedTable,
		"parser/helper.go":           helper,
	})

	got := superseded(modroot, stage, []string{"parser/helper.go", "parser/table.go"})
	if !slices.Equal(got, []string{"parser/helper.go", "parser/table.go"}) {
		test.Errorf("superseded = %v, want both files", got)
	}
}

// Two platform files declare one name all the time, and no build reads them
// together, so a generated platform file is not a redeclaration.
func TestAPlatformFileIsNotARedeclaration(test *testing.T) {
	const linux = "package trash\n\nfunc backend() int { return 1 }\n"
	const darwin = "package trash\n\nfunc backend() int { return 2 }\n"
	modroot := writeTree(test, test.TempDir(), map[string]string{
		"trash/trash_linux.go": linux,
	})
	stage := writeTree(test, test.TempDir(), map[string]string{
		"trash/trash_linux.go":  linux,
		"trash/trash_darwin.go": darwin,
	})

	if got := superseded(modroot, stage, []string{"trash/trash_darwin.go"}); len(got) != 0 {
		test.Errorf("superseded = %v, want nothing dropped", got)
	}
}

// The generator itself carries a build constraint that keeps it out of the
// package, so what it declares is nothing the package declares.
func TestAConstrainedFileDeclaresNothingForThePackage(test *testing.T) {
	const gen = "//go:build ignore\n\npackage main\n\nvar Table = 1\n"
	const generated = "package parser\n\nvar Table = 2\n"
	modroot := writeTree(test, test.TempDir(), map[string]string{
		"parser/gen.go": gen,
	})
	stage := writeTree(test, test.TempDir(), map[string]string{
		"parser/gen.go":   gen,
		"parser/table.go": generated,
	})

	if got := superseded(modroot, stage, []string{"parser/table.go"}); len(got) != 0 {
		test.Errorf("superseded = %v, want nothing dropped", got)
	}
}
